"""Add created_by to expense_group_settlement

Revision ID: 2f2b9b2a3f3b
Revises: 4b1e4db1f12d
Create Date: 2026-02-13 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f2b9b2a3f3b"
down_revision: Union[str, Sequence[str], None] = "4b1e4db1f12d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expensegroupsettlement", sa.Column("created_by", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_expensegroupsettlement_created_by_user", "expensegroupsettlement", "user", ["created_by"], ["id"]
    )
    op.execute("UPDATE expensegroupsettlement SET created_by = debtor_id WHERE created_by IS NULL")
    op.alter_column("expensegroupsettlement", "created_by", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_expensegroupsettlement_created_by_user", "expensegroupsettlement", type_="foreignkey")
    op.drop_column("expensegroupsettlement", "created_by")
    # ### end Alembic commands ###
