"""Add created_at to expense_group table

Revision ID: 36f78f4adf92
Revises: 69fd693fbb60
Create Date: 2026-02-05 11:57:24.763579

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "36f78f4adf92"
down_revision: Union[str, Sequence[str], None] = "69fd693fbb60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server default for existing rows
    op.add_column("expensegroup", sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # Remove server default after all rows have been populated
    op.alter_column("expensegroup", "created_at", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expensegroup", "created_at")
    # ### end Alembic commands ###
