"""Add expense_group_settlement table

Revision ID: 4b1e4db1f12d
Revises: 1e2a0c47d83b
Create Date: 2026-02-13 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b1e4db1f12d"
down_revision: Union[str, Sequence[str], None] = "1e2a0c47d83b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expensegroupsettlement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("debtor_id", sa.Integer(), nullable=False),
        sa.Column("creditor_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["creditor_id"], ["user.id"]),
        sa.ForeignKeyConstraint(["debtor_id"], ["user.id"]),
        sa.ForeignKeyConstraint(["group_id"], ["expensegroup.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_expensegroupsettlement_group_id", "expensegroupsettlement", ["group_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_expensegroupsettlement_group_id", table_name="expensegroupsettlement")
    op.drop_table("expensegroupsettlement")
    # ### end Alembic commands ###
